version: "0.2"

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
      - echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
      - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - kubectl version --client
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 970547352475.dkr.ecr.us-east-2.amazonaws.com

  pre_build:
    commands:
      - echo Building Docker image...
      - ls -la
      - pwd
      - docker build -t level_5/lab .

  build:
    commands:
      - echo Tagging image...
      - docker tag level_5/lab:latest 970547352475.dkr.ecr.us-east-2.amazonaws.com/level_5/lab:latest
      - echo Pushing image to Amazon ECR...
      - docker push 970547352475.dkr.ecr.us-east-2.amazonaws.com/level_5/lab:latest

  post_build:
    commands:
      - echo Deploying application to Kubernetes...
      - kubectl get nodes
      - kubectl apply -f deployment.yaml
      - kubectl get deploy

artifacts:
  files:
    - '**/*'

