apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-pipeline
  template:
    metadata:
      labels:
        app: cicd-pipeline
    spec:

      containers:
      - name: flask-app
        image: docker build -t app .
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: cicd-pipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  
